name: PHPUnit
run-name: PHPUnit
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: php-actions/composer@master

      - name: PHPUnit
        uses: php-actions/phpunit@v3